* 狼塔

#+BEGIN_QUOTE
“When I move, a buffalo moves. When I rest, a mountain reposes. ” — Werner Herzog
#+END_QUOTE

https://www.youtube.com/watch?v=zAdF7m_wwkU

2023年的九月份在考虑国庆行程的时候，我浏览到一位程序员Terry Davis的一个短视频，内容是他闯到一个宁静山区的小图书馆外的花园里，欣赏优美静谧的环境，喃喃自语：“我学会了在一个高度不纯净的环境里如何净化自我。”以色列的魏兹曼研究所提出了人造物的概念（Anthropomass），大致所有人造的物质如建筑，农田，工厂都算来人造物。按估算2020年是人造物质开始在总体上超过自然物质。如果说纯净的环境就是人造物尽量少的地方，那么十月长假何不去一片人造的地方？

此刻，走在北天山山脊一侧的山坡上，除了长在近处山坡上的一丛丛的带刺像仙人掌似的鬼箭锦鸡儿 ，就是散布在各处的稀疏的芨芨草，碱茅和地柏。入秋后变红的野老鹳草特别醒目。时间近乎凝固，耀眼的阳光晒着风化的石头，照在一尘不染的雪坡上。这里也许是地球上少有的最纯净而未被人类物质掺杂的环境。当然，我们脚下的狭窄山路除外，千百年来牧民，马队和徒步者的在坚实砾石路上留下的浅浅的脚印重重叠叠，曲折蜿蜒，通向深处的山岭。

天气晴朗，路边海拔三千多米的山坡上遍布密集丛生的地衣，如同毛边纸上洇开的一滴滴黄色墨水。我边走边歇息，在山坡的碎石路上徐行，一边大口喘气一遍不停眺望积雪覆盖的库拉阿特腾达坂，似近又远。这里的山区与江浙一带的丘陵不同，没有树林遮拦，视野开阔。一根登山杖在第二天翻越白杨沟达坂的雪地是已被折断了杖尖，两根杖虽然经过努力调整长度稍有不同，但尚能借力。仿佛星际穿越里的库珀，驾驶着损毁的耐力号（Endurance），艰难穿越未知的茫茫太空。

达坂是维吾尔语（Dawan）或蒙古语（Davaa,Dabay）的音译，按罗新《从大都到上都》里的说法，拉丁拼音Dabaan，是山口或山坳的意思。如果爱斯基摩人有几十种形容雪的名词，维吾尔人和蒙古人却只用这一种词汇来表达这种地形，大概并不是因为词汇的贫乏，而是这个词汇的唯一用途是作为描述途径地。此行全程海拔大约在两千米以上，最高点是蒙特开增达坂的3950米。物理定律和地球演化决定了唯一个遍布四千米以上高峰的地方是青藏高原，美洲，欧洲和大洋洲普遍两三千米就算高峰。天山是一座中亚地区相对年轻的山脉，不停的地质风化让整个路途往往布满大大小小的碎石，特别是在山区裸露的山峰峡谷之间，经常看到山体滑坡带来的碎石从山顶倾泻而下，仿佛超大规模的石材堆料场，石块锋利的边缘和干净的断面意味着它们也许几百万年前才刚从山体剥落，千年万年的风雨尚未能打磨它们的棱角。荒凉无草也不会因北山羊光顾而被羊蹄踩踏。

十月的长假是七天。九月三十日从上海一大早坐飞机到乌鲁木齐，为了节省路费选择了需要在南阳周转的航班，等入住酒店已经是晚上了，匆忙参加了领队召集的行前会，和康康打了个招呼。十月一日坐了大半天拥挤的小面包车，中午到达山口，匆匆把驮包交给马帮就向山里进发。等走到白杨沟营地天已经黑了。这样两天就过去了。如果扣除回程两天，实际在山里是四天，从第一个营地还要翻过几座达坂真正进入腹地，大约是中间的一两天。仿佛我们跋山涉水，穿过重重阻碍，只为走到冰川面前和它打个招呼，然后就匆匆回家了。我们这些徒步客是去新疆，而不是刘亮程似的“在新疆”。无论旅行多久，新疆始终是一个遥远的梦境而不是现实，即便是深处天山，面对崇山峻岭的时时刻刻，即便凛冽的山风从身上刮过想方设法想从外套的缝隙里带走身上的热量。只有在回到上海，手机屏保程序自动选择老照片的时候，梦境才突然又进入了现实。

丹尼尔卡尼曼在一个对话里说到自己无法参透研究幸福的话题，这牵涉到记忆的自我和经验的自我。旅行是为了以后的记忆，照片是为留下证据。直接经验和间接经验，

然而你也是不知不觉就走进了崇山峻岭：在公路上下车，在路边稍稍热身，就从一条布满碎石的岔路走上了山坡，上了山坡还是公路，跟着公路拐弯以后还是一段几百米的公路。可是不知在第几个弯以后就见不到公路，你突然置身荒野，时间距离下车可能就一个小时。这时你眺望远方，几天后将要翻越的达坂还不知道藏在哪个白茫茫的山峰后面。你从夹在胸口的导水管吸了一口装在背包中鼓鼓囊囊的驼峰水袋里的凉水，太阳从透亮而多云的天空中倾洒下片片阳光晒在你身上稍稍缓解了部分凉意，你心中不由信心满满地感叹，第一天才开始啊！这信心满满的徒步者，确切地知道路途的艰苦，多么希望行程是完美的，身心才能无拘无束应对山野中的劳累，寒冷和畏惧。

然而我的旅行是从慌乱中开始的，一路上出现了各种问题也让这种满满的信心不停地消蚀。我在机场才换了登机牌就丢失了身份证，多方了解才确定可以在手机上申请临时身份令牌，大致不妨碍飞机火车乘坐和酒店入住。但是总觉是丢失了重要证件，心中怅然又惴惴不安，怕有场合非要身份证不免让旅行意外终止。第一天露营就开始下大雪，早上发现没带加厚的抓绒登山裤，更加慌乱了，匆忙在拔营前套了两层单裤御寒，所以走起路来总觉得累赘。第二天翻越白杨沟达坂，因为才下了大雪，没膝的积雪覆盖在碎石坡上，一不小心踩空摔倒，意外折断了右手登山杖的杖尖，还好折断的只是一小节，调节两个登山杖的外锁还能得到差不多的高度，这幅太阳镜是才在年初在丽江古城偶然购买的。但是缺了登山杖尖一侧的手臂总要留意防滑。第三天拔营整装待发，又意外把右侧太阳镜腿折断了，幸好同行的Cherry多带了一副迪卡侬滑雪镜救急，否则可能要在雪地睁不开眼睛了，然而滑雪镜的尺寸较小紧扣在眼眶上颇不舒适。随着丢失和损坏的发生，我的信心如同被风化的山峰逐渐被一层层剥落，担忧慢慢加重。失去的东西仿佛转化为无形的负重压在心上。

第二天从白杨沟达坂到库拉阿特腾达坂还需要反复蹚水穿过台普西马克河，到达一棵树营地，第三天上午继续蹚水穿越水深及腰的尔特兰塔河谷。河水冰冷刺骨，饶是防水长筒袜也无法保持足底的干燥。幸好袜子保证浸润下肢和脚部皮肤的含水层相对静止和温热，没有被冻僵。将近中午，领队通告爬上前方的山坡，就近找干燥的地方午休，大家才如释重负，在土坡向阳的地方坐下休息，午餐和晒太阳，晾晒衣裤和鞋袜。

“所有可见的只是塔的长度。向上或向下看是可怕的，因为连续性的保证已经消失了；他们不再是地面的一部分。这座塔可能是一根悬浮在空中的线，既不附着在地球上，也不能附着在天堂上。”

“All that was visible was a length of the tower. To look up or down was frightening, for the reassurance of continuity was gone; they were no longer part of the ground. The tower might have been a thread suspended in the air, unattached to either earth or to heaven.”

摘录来自
Stories of Your Life and Others
Ted Chiang

在攀登的这一段时间里，希拉勒姆绝望了，感到流离失所，与世界疏远；仿佛大地因为他的不忠而拒绝了他，而天堂却不屑于接受他。他希望耶和华能给出一个信号，让人们知道他们的冒险被批准了；否则他们怎么能呆在一个对精神如此不受欢迎的地方呢？

他们从不担心这对男人来说是一个不合适的地方。没有神圣的保证或鼓励，但人们从来不知道一刻的怀疑。

一路失去和告别的旅程

台普西马克河谷涉溪

此后沿着哈尔噶腾沟一路爬上哈尔噶腾达坂

同行有几位媒体行业的人士，一路用微单相机和无人机跟拍此次徒步旅行。令人想起保罗·西蒙的一首歌《气泡里的男孩》：“镜头以慢动作跟拍我们的方式，是我们所有人审视自己的方式，是我们观测遥远星座的方式，那在天空一角垂死的星座；这是个充满奇迹和惊喜的时代……”

星际穿越：

布兰德：“你知道，我们面临着很大的困难，”她说。 “死亡，但不是邪恶。”

库珀忍不住想确认一下:“你不认为自然是邪恶的吗？”

“不，”她回答道。 “令人敬畏，令人恐惧，但不是，不是邪恶。”

“You know, out there we face great odds,” she says. “Death, but not evil.” Cooper can’t help wondering if that’s correct, “You don’t think nature can be evil?” Brand doesn’t see how. “No,” she replies. “Formidable, frightening, but no, not evil.”

## 遗失之旅

多年前乌孙古道溯溪，冰冷刺骨的融雪溪流，山顶堰塞湖冻得脱水的指尖。狼塔穿越

有人丢失身份证，有人丢失手机，有人徒步鞋底脱胶。

在无边的天山暗夜里，受伤的马伕带走两匹马折返求医，失足跌进台河，第三天尸体在河水中被发现。在飞机上遥望，绵延的戈壁后是整饬的农田，农田背后是皱折的群山，纵横的峡谷中有一簇山峰略高于周围的山峰，在彼处闪闪发光。我仿佛遗失了什么。仿佛离开了新疆又时时想起天山的种种，手机里时时的照片回访让它从梦境走出来变成了日常的现实。

《星际穿越》中布兰德出发前对库珀说：“你知道，我们面临着很大的困难，”她说。 “死亡，但不是邪恶。” 库珀忍不住想确认一下，“你不认为自然是邪恶的吗？”  “不，”她回答道。 “令人敬畏，令人恐惧，但是，不是邪恶。”

[D3 10月1日 白杨沟达坂 ，五星营地](https://www.notion.so/D3-10-1-90642e54b98d4d27bd132c0d5b86f8c2?pvs=21)

[D4 10月2日 台普希克马河谷，一棵树营地](https://www.notion.so/D4-10-2-02bfc3fa48cc4c88aac673cd0d542e13?pvs=21)

[D5 10月3日 库拉阿特腾达坂，尔特兰塔河，狼餐厅营地](https://www.notion.so/D5-10-3-a992303546404fdeba937dd8c670cb78?pvs=21)

[D6 10月4日 蒙特开增达坂，喀拉尕依特达坂，哈尔噶腾郭勒沟 ](https://www.notion.so/D6-10-4-6d3128fba840486ba09685a4cb26c9ab?pvs=21)

[D7 10月5日 哈尔噶腾郭勒沟 河谷 半山营地 哑巴家](https://www.notion.so/D7-10-5-62e2481928e54df7b9ae2525ed115471?pvs=21)

[D8 10月6日 哈尔噶腾（哈拉哈提）达坂3844米（最后一个达坂）焉耆](https://www.notion.so/D8-10-6-3844-eb3e68ef57f54d28a0f418d05dfe8b53?pvs=21)

[misc](https://www.notion.so/misc-06f8fbb91c854398af51460ac0fd7b70?pvs=21)
